openbe_user:
    resource: "@OpenbeUserBundle/Resources/config/routing.yml"
    prefix:   /

openbe_admin:
    resource: "@OpenbeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

