parameters:
#    openbe_admin.example.class: Openbe\AdminBundle\Example

services:
#    openbe_admin.example:
#        class: %openbe_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
